/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        mono: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgba(0, 0, 0, 0.04)',
        soft: '0 2px 10px -2px rgba(99, 102, 241, 0.08), 0 1px 3px 0 rgba(0, 0, 0, 0.03)',
        card: '0 4px 20px -2px rgba(50, 50, 93, 0.06), 0 2px 6px -1px rgba(0, 0, 0, 0.03)',
        elevated: '0 12px 30px -4px rgba(50, 50, 93, 0.09), 0 4px 12px -2px rgba(0, 0, 0, 0.04)',
      },
      colors: {
        brand: {
          50: '#EEF2FF',
          100: '#E0E7FF',
          200: '#C7D2FE',
          300: '#A5B4FC',
          400: '#818CF8',
          500: '#6366F1',
          600: '#4F46E5',
          700: '#4338CA',
          800: '#3730A3',
          900: '#312E81',
        },
        pastel: {
          purpleBg: '#F3F4FD',
          purpleText: '#5A4CE6',
          purpleBorder: '#DDD8FC',
          mintBg: '#ECFDF5',
          mintText: '#047857',
          mintBorder: '#A7F3D0',
          peachBg: '#FFF7ED',
          peachText: '#C2410C',
          peachBorder: '#FED7AA',
          coralBg: '#FFF1F2',
          coralText: '#BE123C',
          coralBorder: '#FECDD3',
          skyBg: '#F0F9FF',
          skyText: '#0369A1',
          skyBorder: '#BAE6FD',
        },
        console: {
          bg: 'var(--bg)',
          panel: 'var(--panel)',
          panelElevated: 'var(--panel-elevated)',
          border: 'var(--border)',
          borderLight: 'var(--border-hover)',
          signal: 'var(--primary)',
          signalHover: 'var(--primary-hover)',
          signalDim: 'var(--primary-light)',
          signalBorder: 'var(--primary-border)',
          mint: '#10b981',
          mintDim: 'rgba(16, 185, 129, 0.12)',
          amber: '#f59e0b',
          amberDim: 'rgba(245, 158, 11, 0.12)',
          cyan: '#0ea5e9',
          cyanDim: 'rgba(14, 165, 233, 0.12)',
          muted: 'var(--muted)',
          textBright: 'var(--text-main)',
          textMuted: 'var(--text-muted)',
        },
      },
      transitionDuration: {
        DEFAULT: '180ms',
        160: '180ms',
      },
    },
  },
  plugins: [],
};
